### PR TITLE
update: Gamedata CSGO Update 02/02/23

### PR DESCRIPTION
**Pull request by crashzk**

### CODE REVIEW

**Comment by Poggicek** [comment]
This signature seems to lead into `ProcessConnectionlessPacket` while the old one lead to `ProcessListenEvents`.

`\x55\x89\xE5\x57\x56\x53\x8D\x5D\x2A\x83\xEC\x64` would be the correct signature

**Comment by crashzk** [comment]
Strange, you no longer receive any errors regarding AntiDLL using the gamedata I sent.

Would you have any error log, step by step to reproduce this error so I can test @Poggicek?

**Comment by stefanx111** [comment]
> This signature seems to lead into `ProcessConnectionlessPacket` while the old one led to `ProcessListenEvents`.
> 
> `\x55\x89\xE5\x57\x56\x53\x8D\x5D\x2A\x83\xEC\x64` would be the correct signature

works!
with the previous gamedata was starting the extension but catch nothing, with this now everything works

**Comment by crashzk** [comment]
Done

**Pull request merged**
